services:
  - type: web
    name: smgts-frontend
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm run preview
    staticPublishPath: ./dist
    envVars:
      - key: VITE_API_URL
        value: https://smgt.onrender.com
